### ISSUE TITLE
Unable to update iOS Deployment Target (minimum iOS version supported)

### ISSUE THREAD

**Issue by hepspl** [skiptools/skip#117]
Created a project using skip init.
Created project was set to iOS 16+.
Used a property which fails as "... is only available in iOS 16.4 or newer"

Tried to fix it by setting deployment target to 17:
- Changed deployment target to 17.0 in Project > Info
- Changed iOS to 17.0 in Project > [Target Name] > General > Minimum Deployments
- Changed IPHONEOS_DEPLOYMENT_TARGET to 17.0 in WhatWatt.xcconfig in Darwin folder

Not working. Building still fails.
- Cleaned build folder. No change.

Checked "iOS Deployment Target" in Target > Build Settings - it's "17.0".

How to update deployment target?
Also how to resign from Mac platform using WhatWatt.xcconfig?

Used property: ".scrollBounceBehavior(.basedOnSize)"
It works in other native project with deployment target 17.0.

_Thank you in advance for advice_

**Comment by marcprux** [comment]
> How to update deployment target?

You will need to additionally set the minimum iOS target in the `Package.swift` file at the top level of your project, which is where all the source files for the app live. E.g.:

```swift
let package = Package(
    name: "myapp",
    platforms: [.iOS(.v17), .macOS(.v13)],
    …
```

> Also how to resign from Mac platform using WhatWatt.xcconfig?

You can configure signing however you want – either in the .xcconfig file, or in the Xcode project itself. If you want to use the  `WhatWatt.xcconfig` file, you can add your signing info like so:

```
CODE_SIGNING_REQUIRED = NO
CODE_SIGN_STYLE = Automatic
CODE_SIGN_ENTITLEMENTS = Entitlements.plist
CODE_SIGN_IDENTITY = iPhone Developer: MyCompany (XXXXXXXXXX)
DEVELOPMENT_TEAM = XXXXXX

```

But it is sometimes easier to configure it in the "Signing & Capabilities" tab of the Xcode project editor, since it will provide better validation and automatically download provisioning profiles.

**Comment by hepspl** [comment]
Perfect, I missed this one spot! Thank you!
