### ISSUE TITLE
Fail to launch the app and "The gradle command failed"

### ISSUE THREAD

**Issue by 1998code** [skiptools/skip#135]
<img width="269" alt="Screenshot 2024-05-31 at 11 17 06 AM" src="https://github.com/skiptools/skip/assets/54872601/96688b8c-55f2-42b5-a1bd-396d0dfc478e">

Any idea? It suddenly not working.

**Comment by 1998code** [comment]
<img width="970" alt="Screenshot 2024-05-31 at 11 34 52 AM" src="https://github.com/skiptools/skip/assets/54872601/7ad5a39a-24e1-4c23-afc8-ead6a80a586a">

**Comment by 1998code** [comment]
https://github.com/1998code/SwiftNEWKit/tree/universal

Source code can be found here.

**Comment by marcprux** [comment]
Did the parent folder name of the project change? It needs to be the same as the Package name in your `Package.swift` file – in your case, it should be "universal". That is the usual cause of the issue.

You may also need to clean and rebuild the project if the parent folder has changed. If that doesn't help, can you let us know the contents of that `DerivedData/…/SourcePackages/plugins/` folder?

**Comment by 1998code** [comment]
Yes, you are right. I renamed the folder and it works again.
Thanks.

**Comment by marcprux** [comment]
Glad it worked! It is an annoying problem, especially since when downloading a project from GitHub as a zip, the project will likely not work out of the box. I'll try to see if we can work around the issue, or at least give a better error message when we identify that the project name does not match the directory name.
