### ISSUE TITLE
[!] Android Studio not found: brew install android-studio

### ISSUE THREAD

**Issue by ihomway** [skiptools/skip#15]
I'm using **Jetbrains Toolbox** to install/upgrade android studio, when I ran command `skip checkup` it said `[!] Android Studio not found: brew install android-studio`.

 Is it possible for a **Jetbrains Toolbox** user to pass the `skip checkup` or install Android Studio via home-brew is required?

**Comment by marcprux** [comment]
I'm not familiar with Jetbrains Toolbox. Does it install Studio somewhere other than `/Applications/Android Studio.app`? That's where the `skip doctor` command checks.

Note also that `skip checkup` should still pass if all it is missing is Android Studio. `skip` never actually invokes Android Studio itself (it uses `gradle` directly for Kotlin builds), but since we expect any app to eventually need to use Studio directly (e.g., for the debugger), we have `skip doctor` (which is part of `skip checkup`) warn when it is missing as a heads-up. As long as all the other checks pass, you can ignore the warning.

**Comment by ahmdyasser** [comment]
@marcprux I use Jetbrains Toolbox and I have the same issue.
Jetbrains Toolbox installs Android to path `/Applications/JetBrains Toolbox/Android Studio.app`

**Comment by marcprux** [comment]
Thanks for the tip. The next version of the skip tool will check in that location as well.

Note that failure to locate Android Studio.app is not a fatal (red) error. It is a (yellow) warning because it is not actually a prerequisite for using Skip: only Gradle is needed. But it is generally recommended, since you will be using Android Studio.app to debug the Kotlin side of the app, which is why we check for it.

**Comment by marcprux** [comment]
skip 0.7.21 will now check for `/Applications/JetBrains Toolbox/Android Studio.app` (as well as `/Applications/Android Studio.app`)
