### ISSUE TITLE
skip checkup can not end

### ISSUE THREAD

**Issue by Abel-Ming** [skiptools/skip#197]
[✓] Skip version 1.0.4 (= 1.0.4)
[✓] macOS version 14.5 (> 13.5.0)
[✓] macOS architecture: ARM
[✓] Swift version 5.10 (> 5.9.0)
[✓] Xcode version 15.4 (> 15.0.0)
[✓] Xcode tools SDKs: 8
[✓] Homebrew version 4.3.15 (> 4.1.0)
[✓] Gradle version 8.10 (> 8.6.0)
[✓] Java version 22.0.2 (> 21.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2023.2
[✓] Android tools SDKs: 6
[✓] Resolve dependencies (23.91s)
[✓] Build hello-skip (12.78s)
[✓] Test Swift (6.78s)
[⠦] Test Kotlin: Build complete! (0.10s)

**Comment by marcprux** [comment]
How long did you let it run? The first time you run, the initial Kotlin build can take quite a long time because it invokes the `gradle` build for the sample app which will have a lot of dependencies on Android Compose libraries. This can wind up downloading quite a lot into your local gradle cache, potentially around 1GB 😮. So if you are on a slow network, these dependencies may take a long time to download.

You could get a more fine-grained view of what is happening by running with the verbose flag (`skip checkup --verbose`), and you should see if it is stuck downloading the dependencies, or if there is some other issue.
