### ISSUE TITLE
How to remove trailiing "App" name from project

### ISSUE THREAD

**Issue by james-mcdougall** [skiptools/skip#30]
Recently found and installed SkipTools and I am already loving it! You guys rock and this is awesome! 

However, as I run the application for testing I notice that on the simulators, the app launches with the name "MyExampleApp" when I just want to have it launch with "MyExample" I have looked through the documentation and have removed any indication of where this could be. I have looked around in the info.plist and the one section that I am finding is to change the name here:

Targets > Build Settings > Project Name:

Changing from "MyExampleApp" to "MyExample" produces build errors. I have even tried creating new schemes and to no resolve. 

It continuously says that I have derived data builds, however I have completely deleted my entire derived data cache. Attached is a screenshot of the error

<img width="1512" alt="Screenshot 2023-11-03 at 10 44 10 AM" src="https://github.com/skiptools/skip/assets/43254528/ee6bc3d9-569b-450c-9667-8eecc72a971d">

Any help would be greatly appreciated!

**Comment by marcprux** [comment]
The trailing "App" is currently required. The way `skip init --appid=… project-name MyExample` works is it creates a pure SPM project with a "MyExample" project and target (plus test cases, etc.). And then, because of the `appid` flag, it creates a `MyExample.xcodeproj` that embeds the `Project.swift` and includes the "MyExample". 

In the Xcode project we create the "MyExample**App**" scheme to launch the whole thing. We can't name it the same as the module itself (Xcode will complain), but you could theoretically name it "MyExample*SomethingElse*".

We recommend just sticking with "App" suffix for the time being, since that is the happy path. You can always rename your app name and other information from the `.xcconfig` file, so the scheme name of "MyExampleApp" shouldn't have any effect on the end product.

We hope to add some more options to the `skip init` command that let you control things like the scheme name. Stay tuned!
